#
# Makefile for the Novatek NT36523 touchscreen driver.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_NT36523_HOSTDL_SPI) += nt36523_touch.o
nt36523_touch-y := nt36xxx.o \
	nt36xxx_fw_update.o
